# Generated by Django 6.0.3 on 2026-03-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_id', models.CharField(max_length=36, unique=True)),
                ('product', models.CharField(max_length=64)),
                ('applicant_id', models.CharField(max_length=128)),
                ('outcome', models.CharField(choices=[('approve', 'Approve'), ('review', 'Review'), ('reject', 'Reject')], max_length=16)),
                ('reason_codes', models.JSONField(default=list)),
                ('model_version', models.CharField(max_length=32)),
                ('prompt_id', models.CharField(blank=True, max_length=64, null=True)),
                ('prompt_version', models.CharField(blank=True, max_length=32, null=True)),
                ('retrieval_sources', models.JSONField(default=list)),
                ('confidence', models.FloatField()),
                ('explanation', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
